GET http://localhost:3000/http-codes

###
POST http://localhost:3000/http-codes
Content-Type: application/json

{
    "code": "OK",
    "message": "OK"
}

###
GET http://localhost:3000/http-codes/62b98762884925af68acba0e

###
PUT http://localhost:3000/http-codes/62b98762884925af68acba0e
Content-Type: application/json

{
    "code": 200,
    "message": "ok"
}
###
DELETE http://localhost:3000/http-codes/62b989c6b1d4a19ea9b679bd

###
GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "ok@ok.com",
    "password": "OKOKOK",
    "firstname": "OK"
}

###
PUT http://localhost:3001/users/2
Content-Type: application/json

{
    "firstname": "O"
}

###
DELETE http://localhost:3000/users/3


###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "ok2@ok.com",
    "password": "OKOKOK",
    "firstname": "OK"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ok2@ok.com",
    "password": "OKOKOK"
}






###
GET http://localhost:5000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E

###
POST http://localhost:5000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E
Content-Type: application/json

{
    "content": "okokko",
    "status": 0,
    "from": 1,
    "to": 2
}

###
PUT http://localhost:5000/messages/changeStatus/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E
Content-Type: application/json

{
    "status": 1
}

###
GET http://localhost:5000/messages/getAllMessagesPerUser/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E

###
DELETE http://localhost:5000/messages/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiT0siLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU4MzM4MTczLCJleHAiOjE2ODk4OTU3NzN9.NmuWfiL7Gf4qdTuxpXhkaiNdsOJhZKvt5SsNyM5cu6E

